name: Update GitHub Activity

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Update GitHub Activity
        uses: ./
        with:
          GITHUB_USERNAME: "thedannicraft"
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          EVENT_LIMIT: 10
          OUTPUT_STYLE: MARKDOWN
          IGNORE_EVENTS: "[]"
          README_PATH: README.md
          COMMIT_MESSAGE: "⚡ Update README.md with latest activity"
